### ISSUE TITLE
Add local.js.example or similar

### ISSUE THREAD

**Issue by zeke** [jbuck/npm-readonly-mirror#1]
I see you've `.gitignore`d the `local.js` file. Can you add a sample config file or some documentation around configuration in general, perhaps in a `CONTRIBUTING.md`?

**Comment by jbuck** [comment]
Yeah, I need to document the process of setting up the S3 bucket and the local client as well.

**Comment by jbuck** [comment]
So, you can `cp dist.json local.json` but the instructions still need more work, because the process of configuring the S3 bucket is actually a PITA!

**Comment by jbuck** [comment]
(Writing docs right now)

**Comment by zeke** [comment]
Sweet!

I should warn you: I'm planning to mention this repo in a Heroku blog post about the new node buildpack tomorrow. Is that okay?

**Comment by jbuck** [comment]
Yep, that's okay! Out of curiousity, is it being used for the nodejs buildpack? Looking forward to reading about it :)

**Comment by jbuck** [comment]
Okay, added some documentation in https://github.com/jbuck/npm-readonly-mirror/commit/e95a3abc0accd7dab7507d73cde51c4729f0a84d . I think I should add some sort of initial config script you run that creates the S3 bucket and cloudfront distribution. That'd probably be a lot easier...

**Comment by zeke** [comment]
Thanks for adding that documentation. Let's see if tomorrow's blog post lights a fire under this project.

We're not currently using this at Heroku, but it's the best implementation of a stable/easy/fast npm mirror that I've seen yet, so we'll see!

**Comment by jbuck** [comment]
Heh, thanks! I'll continue to hack on the documentation until it's in better shape
