### ISSUE TITLE
Fix mirror lag

### ISSUE THREAD

**Issue by stenington** [jbuck/npm-readonly-mirror#5]
We have a pattern with some of our openbadges projects where a core module also has a `*-service` project that builds a frontend around it, e.g. `openbadges-validator` and `openbadges-validator-service`. Often times a bug gets reported that needs to be fixed in the underlying module, then updated in the `*-service` project and that gets deployed shortly after the newest version of the module gets published.

The mirror as it stands can introduce a delay into our ability to deploy the service project, in that we have to wait up to potentially the maximum refresh time before the mirror sees the new version of the underlying module and jenkins can build the service project: https://jenkins.mofoprod.net/job/validator/17/console

One solution could be to update the mirror more often. Another would be to check upstream for unknown versions or projects before failing.

**Comment by jbuck** [comment]
I've lowered the minimum TTL on JSON files to 5 minutes, so that should be an improvement.

I wonder if I just set the TTL to 0, how CF would behave?
