### ISSUE TITLE
404 for /registry/chalk/chalk-0.2.1.tgz

### ISSUE THREAD

**Issue by damaestro** [jbuck/npm-readonly-mirror#7]
npm http GET https://dccmzgc64kzf2.cloudfront.net/registry/chalk/chalk-0.2.1.tgz
npm http 404 https://dccmzgc64kzf2.cloudfront.net/registry/chalk/chalk-0.2.1.tgz
npm ERR! fetch failed https://dccmzgc64kzf2.cloudfront.net/registry/chalk/chalk-0.2.1.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/share/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1601:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

**Comment by jbuck** [comment]
What is your npm registry set to? It looks like it's set to `https://dccmzgc64kzf2.cloudfront.net/registry/`, try setting it to `https://dccmzgc64kzf2.cloudfront.net/`.

**Comment by jbuck** [comment]
Derp. This was an issue on my part. Let me re-sync the package metadata so it's pointing at the correct URL (should be https://dccmzgc64kzf2.cloudfront.net/chalk/chalk-0.2.1.tgz )

**Comment by jbuck** [comment]
All fixed now, thanks for reporting this bug!
