### ISSUE TITLE
Several 404s

### ISSUE THREAD

**Issue by vladikoff** [jbuck/npm-readonly-mirror#8]
Hey, I tried using the readonly mirror and install https://github.com/mozilla/fxa-content-server.
I got several 404s for some packages. i.e:

```
npm http 304 https://dccmzgc64kzf2.cloudfront.net/q/1.0.1
npm http 404 https://dccmzgc64kzf2.cloudfront.net/bower-requirejs/-/bower-requirejs-0.9.2.tgz
npm ERR! fetch failed https://dccmzgc64kzf2.cloudfront.net/bower-requirejs/-/bower-requirejs-0.9.2.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1598:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--registry" "https://dccmzgc64kzf2.cloudfront.net/"
npm ERR! cwd /Users/vfilippov/mozilla/fxa-content-server
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
```

**Comment by jbuck** [comment]
Thanks for reporting this bug!

I'm getting those 404s too. Time to figure out why!

**Comment by jbuck** [comment]
Packages that are 404ing:
- [x] each-async
- [x] bower-requirejs
- [x] vargs
- [x] is-root
- [x] uglify-to-browserify

**Comment by jbuck** [comment]
Okay, I've resynched all 5 packages. It will take up to an hour for the outdated CDN information to be purged from the cache. I'll test installing fxa-content-server then, and let you know if it works.

**Comment by jbuck** [comment]
There seems to be some sort of weird conflict between the npm shrinkwrap and the --registry cli option. If you shrinkwrap something, it always seems to prefer using the registry URL in the shrinkwrap config.

**Comment by jbuck** [comment]
Alright, this should be fixed now. Thanks for reporting this bug!

**Comment by shane-tomlinson** [comment]
Thanks for looking at this @jbuck!

**Comment by vladikoff** [comment]
Yeah indeed! Just tested and it worked perfectly.

**Comment by shane-tomlinson** [comment]
@vladikoff and @jbuck - :beers: I take my hat off to you two for putting in the effort.
